
package br.edu.fa7.emforma.ws.server;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmFormaServiceImplService", targetNamespace = "http://server.ws.emforma.fa7.edu.br/", wsdlLocation = "http://localhost:8080/WS/EmFormaService?wsdl")
public class EmFormaServiceImplService
    extends Service
{

    private final static URL EMFORMASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMFORMASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EMFORMASERVICEIMPLSERVICE_QNAME = new QName("http://server.ws.emforma.fa7.edu.br/", "EmFormaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/EmFormaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMFORMASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EMFORMASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EmFormaServiceImplService() {
        super(__getWsdlLocation(), EMFORMASERVICEIMPLSERVICE_QNAME);
    }

//    public EmFormaServiceImplService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), EMFORMASERVICEIMPLSERVICE_QNAME, features);
//    }

    public EmFormaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EMFORMASERVICEIMPLSERVICE_QNAME);
    }

//    public EmFormaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, EMFORMASERVICEIMPLSERVICE_QNAME, features);
//    }

    public EmFormaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public EmFormaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns EmFormaService
     */
    @WebEndpoint(name = "EmFormaServiceImplPort")
    public EmFormaService getEmFormaServiceImplPort() {
        return super.getPort(new QName("http://server.ws.emforma.fa7.edu.br/", "EmFormaServiceImplPort"), EmFormaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmFormaService
     */
    @WebEndpoint(name = "EmFormaServiceImplPort")
    public EmFormaService getEmFormaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.emforma.fa7.edu.br/", "EmFormaServiceImplPort"), EmFormaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMFORMASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EMFORMASERVICEIMPLSERVICE_EXCEPTION;
        }
        return EMFORMASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
